### ISSUE TITLE
States that we want to launch with 

### ISSUE THREAD

**Issue by ayyubibrahimi** [ayyubibrahimi/us-post-data#19]
A tentative list of states that we should launch with that are referenced in #13. The list is divided into confirmed and holds.

**Confirmed**

- Florida - question

“Separation reason” column is more of an “employment status/change” column - remove “actively employed,” etc., or change name of column?

- Georgia - question

“Separation reason” column is more of an “employment status/change” column - remove “actively employed,” etc., or change name of column?

- Illinois - no notes, but seems like a good model for the "reason for separation" column

- Indiana - question

“Separation reason” column is more of an “employment status/change” column - remove “active,” or change name of column?

- Tennessee - question

No notes, except to ask if things can not be all-caps (this is obviously least urgent)

- Utah - question
No notes, except to ask if things can not be all-caps (this is obviously least urgent)

- Washington - question

“Separation reason” column is more of an “employment status/change” column - remove “certified,” or change name of column? Also if things could not be all-caps

- West Virginia - question

No notes, except to ask if things can not be all-caps (this is obviously least urgent)

- Wyoming - question

Not sure “separation reason” is actually showing that - should we change the name of the column?

**Holds** 

- Alaska - hold for launch?

Data is probably too incomplete for launch, not sure how many officers actually have history, too many other questions about immediate usefulness, and the state is now also being difficult with my update request so not even sure we can immediately promise anything

- Indiana - hold for launch? 

No end dates. 

- Iowa - question

I didn’t see Iowa in the launch data folder - which is fine, but it’s otherwise on my list, so just not sure what to list it as (Ben only sent raw data. This has not been processed). 

- North Carolina - hold for launch?

I don’t see any employment history in the index file

- New Mexico - hold for launch?

Rows in data appear to show employment status or certification changes within individual departments - honestly really not sure what the index file shows

**Maybes**
- Idaho - hold for launch?

Seems like columns reflect employment changes, and certifications, within an agency - hold for launch?

- Maryland - hold for launch?

The rows appear to show employment status changes, like promotions, often within agencies, rather than between - hold for launch?

- Oregon - hold for launch?

The rows appear to show employment status changes, like promotions, often within agencies, rather than between - hold for launch?

- South Carolina - question

Some of the rows appear to show more employment status changes within departments, though other repeated departments appear to be different stints, which would track with our rule about contiguous service being collapsed

Vermont - hold for launch?

The rows appear to show employment status changes, like promotions, often within agencies, rather than between - hold for launch?

**Comment by stecklow** [comment]
Thanks for the additional info @ayyubibrahimi - my [list](https://github.com/ayyubibrahimi/us-post-data/issues/13#issuecomment-2334962672) that I made in #13 was not actually inclusive of every state, just the ones I had any notes about.

Here is the actual full list of potential launch states as I understand them, with their status as I understand it:

- Arizona: no issues
**- Alaska: best to hold for launch**
- California: no issues
- Florida: question about column name
- Georgia: question about column name
- Idaho: question about row collapsing
- Illinois: no issues
**- Indiana: question about column name, and issue with end dates**
- Maryland: question about column names and maybe row collapsing
**- North Carolina: employment history data question, maybe best to hold for launch**
- New Mexico: maybe this is a row collapsing question?
- Oregon: row collapsing question
- South Carolina: row collapsing question
- Tennessee: no issues
- Utah: no issues
- Vermont: row collapsing question
- Washington: question about column name
- West Virginia: no issues
- Wyoming: question about column name

I removed Iowa from this because for some reason I previously thought it had been processed. 

I also may receive processed Indiana data this week, if it comes in time to utilize, so that's why I left it there. If it's too late regardless for launch, that's fine and we can keep it off the list.

**Comment by ayyubibrahimi** [comment]
Based on the list above, does this order make sense? 

Confirmed for launch:
- Arizona: no issues
- California: no issues
- Illinois: no issues
- Tennessee: no issues
- Utah: no issues
- West Virginia: no issues

States with column names issues. @stecklow can suggest some appropriate column names? : 
- Florida: question about column name
- Georgia: question about column name
- Maryland: question about column names and maybe row collapsing
- Washington: question about column name
- Wyoming: question about column name

States with non-collapsed rows. @tarakc02 I think that the row collapsing question is one for you:  
- Idaho: question about row collapsing
- New Mexico: maybe this is a row collapsing question?
- Oregon: row collapsing question
- South Carolina: row collapsing question
- Vermont: row collapsing question

Hold off for launch: 
- Alaska: best to hold for launch
- Indiana: question about column name, and issue with end dates**
- North Carolina: employment history data question, maybe best to hold for launch**

Additionally, the list above doesn't contain Texas, Kentucky, and Ohio which are listed as processed in the issue here #13 . Are we skipping these for the launch?

**Comment by ayyubibrahimi** [comment]
Based on this list, I pushed a prototype for Azirona at: https://national.cpdp.co/state/Arizona which includes an about modal. I think that we should start testing the confirmed states beginning next week.

**Comment by ayyubibrahimi** [comment]
All good. Some of these changes were made, but some say "employment_status" still. I'll add it to the list of things to change for the next iteration.

**Comment by ayyubibrahimi** [comment]
Before I re-run the pipeline now that Tarak has integrated his code into the base, can we confirm that these are the states that have rows that need to be collapsed @stecklow ?

States with non-collapsed rows:

Idaho: question about row collapsing
New Mexico: maybe this is a row collapsing question?
Oregon: row collapsing question
South Carolina: row collapsing question
Vermont: row collapsing question

**Comment by stecklow** [comment]
And Maryland was also in my notes in this category. Thanks!

**Comment by ayyubibrahimi** [comment]
Thanks.

**Comment by ayyubibrahimi** [comment]
Final list: 
- "Arizona", '
- California', 
- "Florida",
- "Georgia", 
- "Illinois", 
- "Kentucky",
- "Maryland", 
- "Idaho", 
- "Ohio", 
- "Oregon", 
- "New Mexico", 
- "South Carolina", 
- "Tennessee", 
- "Texas", 
- "Utah", 
- "Washington",
-  "Vermont",
- "West Virginia", 
- "Wyoming"
