### ISSUE TITLE
Search Bug

### ISSUE THREAD

**Issue by MattInternet** [ayyubibrahimi/us-post-data#26]
The Search appears to be missing some results that there is data for.

For example there is an officer in [Utah](https://national.cpdp.co/state/Utah) named `John S Beener`

Searching for lastname `Beener` firstname `John` in the webui does not return him and the actual response is empty. The request appears to be correct though: `https://national.cpdp.co/api/fetchStateData?state=Utah&page=1&pageSize=10&lastName=Beener&firstName=John`

Removing his first name and only searching for lastname `Beener` does work, and that request also looks correct: `https://national.cpdp.co/api/fetchStateData?state=Utah&page=1&pageSize=10&lastName=Beener`

**Comment by ayyubibrahimi** [comment]
Fixed in PR [#19](https://github.com/ayyubibrahimi/us-post-front-end/pull/19) in the front-end repo. Thank you!

**Comment by MattInternet** [comment]
@ayyubibrahimi I dont mean to bug you but is that merged PR deployed? I still get search errors with valid searches, for example: `https://national.cpdp.co/api/fetchStateData?state=Utah&page=1&pageSize=15&lastName=Graham&firstName=Karl` returns a 500

**Comment by ayyubibrahimi** [comment]
hi @MattInternet can you try it again now?
