### ISSUE TITLE
california flattening and agency names

### ISSUE THREAD

**Issue by tarakc02** [ayyubibrahimi/us-post-data#27]
when i build the california output using the code in the repo, the code from #6 correctly flattens contiguous stints into one row. But looking things up on the site, those records appear disaggregated. For example when I look up last name "ourjanian", I see adjacent stints at "Sierra CO Sheriff's Office Office". When I build locally and look at the `upload` folder, I see those correctly collapsed to one stint, and further the agency is just named as "Sierra CO Sheriff's Office" (without the redundant second "Office").

**Comment by ayyubibrahimi** [comment]
Fixed in PR #28. Thanks!
