### ISSUE TITLE
WV: new data

### ISSUE THREAD

**Issue by ayyubibrahimi** [ayyubibrahimi/us-post-data#32]
https://www.dropbox.com/scl/fo/e1xaraxmtjvpf5iz1yzqx/AMTOZInv_4fo8FfGBiHwXv0?rlkey=23wcgwybblwazy6nks6siegpv&dl=0

**Comment by ayyubibrahimi** [comment]
The new data that Sam mentioned above: https://www.dropbox.com/scl/fo/8xcjvub3gmf5ywxiwhif7/AHS4b0rpoYB_I2cO1x_MTQ0?rlkey=89nxkdwbp6j7n7k7d50xbkv4h&dl=0

**Comment by stecklow** [comment]
To clarify in writing, the file that Ayyub posted is the full new WV data - the first post in this issue is a separate file that should be disregarded

**Comment by ayyubibrahimi** [comment]
This was processed and uploaded to the WV [folder](https://www.dropbox.com/scl/fo/lsearmlbu84b3nx8wi0i4/ADuhsBHWQWiKBLmkgEfsi3w?rlkey=4cb6coufr552mkw4jw9x02eur&st=8wr8xb5w&dl=0).
