### ISSUE TITLE
Kansas

### ISSUE THREAD

**Issue by tarakc02** [ayyubibrahimi/us-post-data#35]
[data](https://url.avanan.click/v2/___https://www.dropbox.com/scl/fo/ersykuvzt32dd7d70xd7k/APVe23r1FRoScwu6xxV6NDc?rlkey=s5md5wk85b3r7bud0j3d4zkjt&dl=0___.YXAzOmlwbm86YTpvOjQ2NDdlZmU0ZDljYTY0MTM5MmQ3Zjg4NGI1ODE5NTBmOjY6NjUxMjplOGQ5MzAwMWExOGJlYWVkNzMzZjQ1M2MxZTRhMGQ5YjFiMmFiY2MxMmQ3ODYwN2I5OWQ5ZTBhYzM1MDZlODczOmg6VDpO)

**Comment by tarakc02** [comment]
assigned to [argolb](https://github.com/argolb)

**Comment by argolb** [comment]
@tarakc02 KS is ready for review.

**Comment by tarakc02** [comment]
I've created PR #39, we'll review the two requested updates on Tuesday morning, but overall this looks good to me! should be able to merge during our meeting.

**Comment by tarakc02** [comment]
@ayyubibrahimi data is processed, uploaded to dropbox, and gets downloaded in preprocess/download. let us know if there's anything else we need to do here. thanks
